### ISSUE TITLE
Information 

### ISSUE THREAD

**Issue by Umarkamboh** [Xstar97/TXI#101]
xposed framework  zip not work in my rom. just hang on bootloop.(samsung mono)...

Debug info:
 OS Version: 3.4.0-DarkLord-Kernel-Marshmallow-hlte-eur-V1.9(G935FXXU1APEK)
 OS API Level: 23
 Device: hero2lte
 Model (and Product): SM-G935F (hero2ltexx)
 RELEASE: 6.0.1
 BRAND: samsung
 DISPLAY: DarkLord.S7E.G935FXXU1APEK
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: 
Framework is NOT installed!
APP Version: 1.0
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd info: cd /storage/emulated/0/Android/data/com.mcs.terminalinstallerx/files/Download/wanam-xposed/
DIR Info: /storage/emulated/0/Android/data/com.mcs.terminalinstallerx/files/Download/wanam-xposed/flash-script.sh
stack.trace does NOT exist

**Comment by Xstar97** [comment]
okay, the issue seems to stem from the custom rom probably more specifically the kernal(maybe)..do you need this custom rom? 
since xposed may worked on a pure touchwiz(samsung) rom

**Comment by Umarkamboh** [comment]
Previously i flashed note 5 custom rom on my note 3 device. on that rom xposed correctly worked but when i flashed s7 egde rom its not worked...

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 18:10, Xstar97<notifications@github.com> wrote:   
okay, the issue seems to stem from the custom rom probably more specifically the kernal(maybe)..do you need this custom rom? 
since xposed may worked on a pure touchwiz(samsung) rom

**Comment by Xstar97** [comment]
then reflashed the previously working custom rom or revert back to stock...you may also want to contact the developer for more info as to why his custom rom doesnt work with xposed

**Comment by Umarkamboh** [comment]
Ok... but i flashed 4 or 5 different rom. Every rom has same issue..

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 18:23, Xstar97<notifications@github.com> wrote:   
then reflashed the previously working custom rom or revert back to stock...you may also want to contact the developer for more info as to why his custom rom doesnt work with xposed
