### ISSUE TITLE
Script tampering

### ISSUE THREAD

**Issue by mschandler76** [Xstar97/TXI#103]
Keeps giving me a warning about script tampering then says it's not compatible. 

Debug info:
 OS Version: 3.4.0-4432708(G900FXXU1BPA2)
 OS API Level: 21
 Device: klte
 Model (and Product): SM-G900F (kltexx)
 RELEASE: 5.0
 BRAND: samsung
 DISPLAY: PhoeniX ROM V11.0 XXU1BPA2
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: 
Framework is installed!
APP Version: 1.0
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
stack.trace does NOT exist

**Comment by Xstar97** [comment]
were there any red lines in the script preview?
IE framework version, abi, sdk, etc?
it could be the md5 is not saving...have you deleted the previous framework & re-downloaded it?

**Comment by mschandler76** [comment]
Nope no red lines that I saw. I'm redownloading everything now to test out
the install then I'm going to revisit the no uninstall thing. Can't really
say its a problem since I've never had a need to to uninstall
it....probably like most people. But I'm sure there are times.

On Aug 24, 2016 5:05 AM, "Xstar97" <notifications@github.com> wrote:

were there any red lines in the script preview?
IE framework version, abi, sdk, etc?
it could be the md5 is not saving...have you deleted the previous framework
& re-downloaded it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Xstar97/TXI/issues/103#issuecomment-242001735>, or mute
the thread

**Comment by mschandler76** [comment]
Ok on installing it doesn't install, I get the closed.prop not found. This
happened before I remember.

**Comment by Xstar97** [comment]
did you try all the cd methods?

**Comment by mschandler76** [comment]
No I didn't. I gotta keep  that in mind, I'm on my way in to work and I'll
do that. There's three right?

**Comment by Xstar97** [comment]
yes..
1. storage(default)
2. sdcard
3. mnt

this way any user doesnt worry about the stderr bug

**Comment by mschandler76** [comment]
Gotcha. Mnt worked, default didn't and I didn't try sdcard. But it does
work.

**Comment by Xstar97** [comment]
okay...good to hear....I took the liberty of modifying the script execution system to be more fluent & easier to maintain in a way that's now modular...& i am also looking into any issues if the tool cant decide which framework to download, to load, & finally execute (install/uninstall) so I need more testers....also when installing & uninstalling you need to reboot after each one or issues may rise....i am planning on adding the reboot dialog if the execution is successful. But it wont be mandatory though.

**Comment by mschandler76** [comment]
Cool, and yes a reboot is definitely necessary...at least for me. As soon
as it loaded the framework everything started stopping. So for me a reboot
is absolutely necessary.

**Comment by mschandler76** [comment]
Ok after flashing the uninstall and starting from scratch. Install went perfect and everything is running as normal. Now I'm revisiting the uninstall issue, so when I select to uninstall it displays a warning about script tampering. I hit ok the app says removing tampered data then quickly restarts the process, it goes back to the execute script selection. If I select execute script it says framework not compatible with device and asks if I'd like to send a report. If I don't select execute and just hit the red x in the top left corner it'll let me do the whole process over again, over and over.

**Comment by Xstar97** [comment]
Its the md5 check stopping the process.... So I will add the previous
uninstall script back later

**Comment by Xstar97** [comment]
I just updated the uninstaller so it should be a few minutes before it can be publicly accessed...so clear the app's data with the clear data option in manage & check back soon....also a new & improved beta will be released soon as soon as I finish some stuff.

**Comment by Xstar97** [comment]
can you tap the facebook button in the social section of About...my tool uploaded a crash when a user tapped it. also did you try out the latest version yet?

**Comment by mschandler76** [comment]
Yea I've got the new version. It still doesn't let me uninstall under all
three methods. But now it freezes after I select execute, then gives me the
tampered data dialogue but feezes until the system crash box displays.

And yes I can tap the Facebook button, no problem with that. I'll try the
others as well.

**Comment by Xstar97** [comment]
Can you report a new issue & then clear the tools data...don't reflash w/
flash fire yet...& update the tools data with a pull request from txi

**Comment by mschandler76** [comment]
Yeah gimme just a bit. I'm out and I'll submit a new report.
