### ISSUE TITLE
Changing of font or language.

### ISSUE THREAD

**Issue by mschandler76** [Xstar97/TXI#118]
Not really a bug but the languages and fonts don't change when selected. It just says selected null.

-

Device info:
---
<table>
<tr><td>App version</td><td>1.7</td></tr>
<tr><td>App version code</td><td>8</td></tr>
<tr><td>Android build version</td><td>G900FXXU1BOD3</td></tr>
<tr><td>Android release version</td><td>5.0</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>XtreStoLite INTL v.2.2 - XXU1BOD3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>klte</td></tr>
<tr><td>Device model</td><td>SM-G900F</td></tr>
<tr><td>Device product name</td><td>kltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>is rooted?</td><td>true</td></tr>
<tr><td>are busybox utilities installed?</td><td>true</td></tr>
<tr><td>is framework installed?</td><td>false</td></tr>
<tr><td>xposed installer app info</td><td>is not installed!</td></tr>
<tr><td>stack.trace</td><td>java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mcs.terminalinstallerx/com.mcs.terminalinstallerx.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.ads.InterstitialAd.isLoaded()' on a null object reference

--------- Stack trace ---------

    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
    android.app.ActivityThread.access$900(ActivityThread.java:172)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

--------- Cause ---------

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.ads.InterstitialAd.isLoaded()' on a null object reference

    com.mcs.terminalinstallerx.activities.MainActivity$2.onTabSelected(MainActivity.java:157)
    com.roughike.bottombar.BottomBar.setOnTabSelectListener(BottomBar.java:343)
    com.mcs.terminalinstallerx.activities.MainActivity.onCreate(MainActivity.java:154)
    android.app.Activity.performCreate(Activity.java:6221)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
    android.app.ActivityThread.access$900(ActivityThread.java:172)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

</td></tr>
</table>

**Comment by Xstar97** [comment]
Please either clear the app's data through system or uninstall and reinstall.
I just checked it myself and it works for me....but before you try the two options...did you tap restart after?

**Comment by mschandler76** [comment]
Wait is the app utilizing what fonts I have internally? If so its my phone.

On Sep 17, 2016 3:44 PM, "Xstar97" <notifications@github.com> wrote:

Please either clear the app's data through system or uninstall and
reinstall.
I just checked it myself and it works for me....but before you try the two
options...did you tap restart after?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Xstar97/TXI/issues/118#issuecomment-247802681>, or mute
the thread

**Comment by Xstar97** [comment]
No....my tool loads the fonts from my assets folder & all my fonts are custom...when you select an option for fonts...does it say "Selected null" or its name with the font changed?

**Comment by mschandler76** [comment]
Ah OK. Just says selected null.

**Comment by Xstar97** [comment]
Still?
It works for me!

**Comment by mschandler76** [comment]
Yeah, but I think it's my phone and this ROM I installed. It's completely
slimmed down. And initially when setting it up I accidentally told the
aroma adon that I didn't want something with accessibility. I had to go
back and get it. Cause I know it did work fine before.

**Comment by Xstar97** [comment]
whats the rom called?

**Comment by mschandler76** [comment]
XtreStoLite INTL v2.2 XXU1BOD3

Works pretty well, but has some quirks. Hopefully gonna be getting a new
phone soon.

**Comment by Xstar97** [comment]
I believed its now fixed & fully operational.
