### ISSUE TITLE
Wont run after i did resent update.

### ISSUE THREAD

**Issue by xSage132** [Xstar97/TXI#139]
Please helo me man i really love your app but when i updated it it just wont load but gives me "app isnt responding". Please help me.

**Comment by Xstar97** [comment]
Okay, for me to diagnose the problem...I need your device info & can you grab a file from /data/data/com.terminalinstallerx/files/ stack.trace

You can upload the file here or its contents

-Its a file that loads crash data...so it will tell me what went wrong. So for clarification does it crash every time you start the app?

**Comment by Xstar97** [comment]
@xSage132 can you provide me the info so I can diagnose the problem?

**Comment by Xstar97** [comment]
@xSage132 I found the problem...it was my PC I am a windows insider so testing the latest crapdate of windows made my PC unreliable...any changes I made in android studio were never saved (PC frozed half the time) & the released version that I built was defective...so I did a quick few test & fixed some other bugs..so the update should be live soon!

**Comment by xSage132** [comment]
Hey i actually got around it by installing previous version. But if you
still want the crash report then let me know😃

**Comment by Xstar97** [comment]
Actually Terminal installer X is not supported anymore. The original developer of xposed(rovo89) & others made a new version of xposed installer 3.1 & just like the original it actually works & it now has material design & can flash xposed without a custom recovery.

So go to "attach files" & download & install v3.1

http://forum.xda-developers.com/showthread.php?t=3034811

**Comment by xSage132** [comment]
Alright thank you
