### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by Xstar97** [Xstar97/TXI#26]
frameworkwill not install correctly.!! 20 or 30 tries!!

Debug info:
 OS Version: 3.10.61-7368506(G920AUCS4CPF1)
 OS API Level: 23
 Device: zeroflteatt
 Model (and Product): SAMSUNG-SM-G920A (zeroflteuc)
 RELEASE: 6.0.1
 BRAND: samsung
 DISPLAY: MMB29K.G920AUCS4CPF1
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: samsungexynos7420
 MANUFACTURER: samsung

Extra Info: java.lang.NumberFormatException: Invalid int: "85.1"

--------- Stack trace ---------

    java.lang.Integer.invalidInt(Integer.java:138)
    java.lang.Integer.parse(Integer.java:410)
    java.lang.Integer.parseInt(Integer.java:367)
    java.lang.Integer.parseInt(Integer.java:334)
    com.mcs.txi.dialogs.DialogFrameworkInstaller.prop_framework_ver(DialogFrameworkInstaller.java:468)
    com.mcs.txi.dialogs.DialogFrameworkInstaller.onCreateView(DialogFrameworkInstaller.java:143)
    android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
    android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:158)
    android.app.ActivityThread.main(ActivityThread.java:7229)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
-------------------------------

--------- Cause ---------

-------------------------------

**Comment by Xstar97** [comment]
This was recently fix & the version 2.2 should be live soon...please expect many updates this week...Thanks for reporting it!

**Comment by easterm** [comment]
.

**Comment by Xstar97** [comment]
@easterm 
Yes...I made a very stupid mistake trying to make this "85.1" into an integer for comparing....However certain parts of my tool had that code still in placed...even though I did try to remove it...it still lingered to haunt me!...so in v3(16)...I added some logic to compare the frameworks with "." by string.equals instead throughout the entire tool...so if you are having an issue with Terminal Installer X...it will be updated on July 1st, 2016!
