### ISSUE TITLE
Sorry still freezing

### ISSUE THREAD

**Issue by mschandler76** [Xstar97/TXI#64]
Almost completely verbatim as before except the system close and report may or may not appear. So to be sure I uninstalled the app and did a system clean with sd maid pro. Rebooted then reinstalled but it froze up at the same spot waiting at the end of the framework download. I also tried your suggestion to clear data and cache in apps settings but had the same result. The pulldown menu works normal this time though, I forgot to mention that the first time it didnt. 

Debug info:
 OS Version: 3.4.0-4432708(G900FXXU1BPA2)
 OS API Level: 21
 Device: klte
 Model (and Product): SM-G900F (kltexx)
 RELEASE: 5.0
 BRAND: samsung
 DISPLAY: PhoeniX ROM V11.0 XXU1BPA2
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: 
Framework is NOT installed!
APP Version: 3.2.1
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mcs.txi/com.mcs.txi.activities.Gitty}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference

--------- Stack trace ---------

    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
    android.app.ActivityThread.access$900(ActivityThread.java:172)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

--------- Cause ---------

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference

    com.mcs.txi.activities.Gitty.dir_info(Gitty.java:160)
    com.mcs.txi.activities.Gitty.init(Gitty.java:61)
    com.github.paolorotolo.gitty_reporter.GittyReporter.onCreate(GittyReporter.java:69)
    android.app.Activity.performCreate(Activity.java:6221)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
    android.app.ActivityThread.access$900(ActivityThread.java:172)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

**Comment by Xstar97** [comment]
Sorry...but I am not seeing the issue with the downloader...the stacktrace is probably being updated from the new crash...I'm going to re check my code...
but can you check if "frameworkinfoprefs.xml" exist in my sharedprefs folder...you will need to use a rooted file explorer to go to /data/data/com.mcs.txi/sharedprefs/
If the file exist...then see if anything is written in it too

**Comment by mschandler76** [comment]
Yep everything is there and data is written in the xml file. I don't
neccesarilly think it's the download portion, but that's just where it
stops and freezes.

**Comment by Xstar97** [comment]
Does "deviceInfopref.xml" exist too?

**Comment by mschandler76** [comment]
Yes it's there, data written in it as well.

**Comment by Xstar97** [comment]
Delete that file, redownload the framework & wait for the crash & then try to report it again

**Comment by Xstar97** [comment]
I am about to released a new version...but the easy fix is to unzip the file thats downloaded yourself & restart Terminal Installer X...if you dont want to wait anymore for an update that may do the same thing...I am truly sorry this has happen & I am truly glad you took the time & effort to report the issue.

**Comment by mschandler76** [comment]
It's fine I can wait for the new version. Ive just started trying to learn
coding so this has been helpful in understanding the bug hunting portion.
On Jul 8, 2016 8:22 PM, "Xstar97" <notifications@github.com> wrote:

I am about to released a new version...but the easy fix is to unzip the
file thats downloaded yourself & restart Terminal Installer X...if you dont
want to wait anymore for an update that may do the same thing...I am truly
sorry this has happen & I am truly glad you took the time & effort to
report the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Xstar97/TXI/issues/64#issuecomment-231501949>, or mute
the thread
<https://github.com/notifications/unsubscribe/ATa3FWNjShQWQwYRw9OkgULRnw3LC_6rks5qTunRgaJpZM4JIdi0>
.
