### ISSUE TITLE
Freeze resubmit

### ISSUE THREAD

**Issue by mschandler76** [Xstar97/TXI#68]
Here you go, hopefully the info you need is there now. I have to clear cache to send the report after the crash. I think the last time I tried to send it and had to wait for the crash then sent after THAT crash, which was a crash waiting to send the original crash.... Hope that's not too confusing. 

Debug info:
 OS Version: 3.4.0-4432708(G900FXXU1BPA2)
 OS API Level: 21
 Device: klte
 Model (and Product): SM-G900F (kltexx)
 RELEASE: 5.0
 BRAND: samsung
 DISPLAY: PhoeniX ROM V11.0 XXU1BPA2
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: 
Framework is NOT installed!
APP Version: 3.2.1
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference

--------- Stack trace ---------

    com.mcs.txi.dialogs.DialogScript.<init>(DialogScript.java:376)
    com.mcs.txi.dialogs.DialogDownload.script(DialogDownload.java:209)
    com.mcs.txi.dialogs.DialogDownload.xposedchecker(DialogDownload.java:201)
    com.mcs.txi.dialogs.DialogDownload.crashchecker(DialogDownload.java:197)
    com.mcs.txi.dialogs.DialogDownload.dkcldarkunzip(DialogDownload.java:292)
    com.mcs.txi.dialogs.DialogDownload.access$1000011(DialogDownload.java)
    com.mcs.txi.dialogs.DialogDownload$DownloadTask.onPostExecute(DialogDownload.java:180)
    com.mcs.txi.dialogs.DialogDownload$DownloadTask.onPostExecute(DialogDownload.java)
    android.os.AsyncTask.finish(AsyncTask.java:632)
    android.os.AsyncTask.access$600(AsyncTask.java:177)
    android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

--------- Cause ---------

-------------------------------

**Comment by Xstar97** [comment]
I was able to fix the issue with this stacktrace...thank YOU for helping me figure it out...the tool actually downloads, unzips the framework, but crashes when dialogScript is launched...NOT the downloader...so I moved the code around that caused this issue & it should be fixed now.
