### ISSUE TITLE
Freezing still

### ISSUE THREAD

**Issue by mschandler76** [Xstar97/TXI#69]
Man your gonna get tired of me. So the framework download goes through then disappears but it freezes then crashes afterwords. Now the system crash notification of Google Dev pops up after I hit ok it went away after the last couple of updates. 

Debug info:
 OS Version: 3.4.0-4432708(G900FXXU1BPA2)
 OS API Level: 21
 Device: klte
 Model (and Product): SM-G900F (kltexx)
 RELEASE: 5.0
 BRAND: samsung
 DISPLAY: PhoeniX ROM V11.0 XXU1BPA2
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: 
Framework is NOT installed!
APP Version: 3.2.2
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference

--------- Stack trace ---------

    com.mcs.txi.dialogs.DialogScript.onCreateView(DialogScript.java:111)
    android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
    android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

--------- Cause ---------

-------------------------------

**Comment by Xstar97** [comment]
To be honest I am GLAD that you are reporting the issues...But sad that the issues are now occuring(or were always occuring to begin with)..can you please check if dkcldark-xposed folder exist in this directory?
"/sdcard/Android/Data/com.mcs.txi/Download/dkcldark"
I now believe it cant unzip fast enough on samsung devices before launching the script dialog...this is the reason why its always crashing because it cant load  a file that is not there

**Comment by Xstar97** [comment]
before releasing v3.2.3...could you beta test it to see if will still crash?
http://www.mediafire.com/download/s6qi41agqb37a3d/app.apk

**Comment by Xstar97** [comment]
I wrapped a timertask to be executed after the download has finish & until the unzipping is complete the script dialog will launch

**Comment by mschandler76** [comment]
Sorry for the delay... I had to sleep a bit.
But no there is no dkcldark folder. Matter of fact not even a download
folder only "files"

**Comment by Xstar97** [comment]
Please try to download it again...then check if the folder/zip exist

**Comment by Xstar97** [comment]
is there an issue that keeps it from downloading or does it crash after downloading?

**Comment by mschandler76** [comment]
Ok I saw the test on mediafire and got it. Downloaded and now there IS a
folder and files inside of the dkcldark folder. But crashes after that.

**Comment by Xstar97** [comment]
open up terminal installer & check in manage the size of the data folder..if its less than 7MB than its failing to unzip it
(storage estimate)

**Comment by mschandler76** [comment]
Yes before this test version there was no dkcldark folder. With the test
version there is but then crashes after it finishes the download and
extraction of the files?

**Comment by Xstar97** [comment]
most likely my tool is trying to extract the zip while its trying to delete it..though going to change that in a sec

**Comment by mschandler76** [comment]
It shows 13.7

**Comment by Xstar97** [comment]
can you exit the tool & restart it(dont clear the data)...does the downloader still pop up even if its downloaded?

**Comment by Xstar97** [comment]
Okay...I think I now know the cause of the crash....its how I load the script universally in my tool..its most likely returning null...resulting in a crash

**Comment by mschandler76** [comment]
Nope it crashes when I do it.

**Comment by Xstar97** [comment]
Yep..so I will have to modify how I load the script in the dialog..so give me a few to do that & I will send you the beta..thanks for helping me out!

**Comment by mschandler76** [comment]
Was that something you changed recently? A previous version last week did
work (16) or (17) but I'm not sure. But I wondered if it was something on
my side because I had to do a complete system restore with my phone. Messed
with my build.prop too much. But I restored it back with everything the
same as before.

**Comment by Xstar97** [comment]
Its my fault..I was using so much lines of code...so I created a method with switch statements to load the scripts, cd info, & dir universally for all framework varient from one location dynamically...however it does work with the original..so I dont know why it wouldnt work with samsung...so ATM its rebuilding the tool & I will upload soon
build 16/17 and lower had the same code written over & over again...with only 1 line changed...so i didnt want that since it was hard to maintain & make it readable
I went from 2000 lines of code to 381 in the ScriptDialog!
its now easier for me to debug & fix issues...so thanks for reporting again...I would have never figure it out without you!

**Comment by Xstar97** [comment]
heres the latest build...I tested on my shield TV  & but not my LGK7...however I dont have a samsung device...its been really hard to support that manufacturer..so...let me know if it works or not
http://www.mediafire.com/download/z93dtp4bhwyewt4/app.apk

**Comment by mschandler76** [comment]
Man I feel bad everytime I gotta tell you it freezes at the same place
again. I know your working hard on it. But same place, files are in the
dkcldark folder.

**Comment by Xstar97** [comment]
can you report the issue ...I want to see if the stacktrace is the same or not

**Comment by mschandler76** [comment]
Will do, also would a log cat from my side help you? Or do you get that
automatically when I send the report?

**Comment by Xstar97** [comment]
I dont need a logcat...however my tool creates a stacktrace of the exception that occured for my app...its automatically loaded into every issue reported

**Comment by mschandler76** [comment]
Ok it's sent.
