### ISSUE TITLE
Freeze (new)

### ISSUE THREAD

**Issue by mschandler76** [Xstar97/TXI#72]
Same as discussed. 

Debug info:
 OS Version: 3.4.0-4432708(G900FXXU1BPA2)
 OS API Level: 21
 Device: klte
 Model (and Product): SM-G900F (kltexx)
 RELEASE: 5.0
 BRAND: samsung
 DISPLAY: PhoeniX ROM V11.0 XXU1BPA2
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: 
Framework is NOT installed!
APP Version: 3.2.3
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
java.lang.NumberFormatException: Invalid int: ""

--------- Stack trace ---------

    java.lang.Integer.invalidInt(Integer.java:138)
    java.lang.Integer.parseInt(Integer.java:358)
    java.lang.Integer.parseInt(Integer.java:334)
    com.mcs.txi.utils.Xposed.VersionInstalled(Xposed.java:68)
    com.mcs.txi.utils.Xposed.XposedInstalledVersion(Xposed.java:13)
    com.mcs.txi.utils.Scripts.Dir(Scripts.java:404)
    com.mcs.txi.utils.Scripts.ScriptDir(Scripts.java:10)
    com.mcs.txi.dialogs.DialogScript.onCreateView(DialogScript.java:111)
    android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
    android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:145)
    android.app.ActivityThread.main(ActivityThread.java:5832)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
-------------------------------

--------- Cause ---------

-------------------------------

**Comment by Xstar97** [comment]
okaay so I just wrapped the strings that may caused the crashed in an if/statement..so if the data is null...it wont crash anymore...but nothing will be loaded...so when i send you a new link make sure to check the script to see if its says
"Error loading from file!"
also I figured it out maybe again...so give me a few to rebuild the tool

**Comment by Xstar97** [comment]
im positive it wont crash anymore
http://www.mediafire.com/download/uul1yedhfbh8zzd/terminal.apk

**Comment by Xstar97** [comment]
I am having issues with my IDE...it seems all my issues have always stemmed from it since the last 3 updates of my IDE...so its going to be a few days before I can start working on the build since the IDE is not building my app with the changes I made

**Comment by mschandler76** [comment]
Oh man...so it's been the same file basically each time?

Cause I was just replying in another email that it's freezing at the same
place, but I do see the "error loading from file" in your script. Just dont
see a log for what happened if that's what you mean. Of course I may be
looking in the wrong place...

**Comment by Xstar97** [comment]
its not the same apk..but the build is not actually being generated..so I am going to have to test some other things out before the actual release..sorry for replying back so late...I needed to do some more research

**Comment by mschandler76** [comment]
No problem, its Saturday so I would expect things to take longer.

**Comment by Xstar97** [comment]
So I decided to create a universal folder instead of a folder for each varient...this way the methods will stay the same & hopefully not crash anymore...but ATM I am not working, but will fix the issues soon...so thanks for all the help, reports & waiting all this time for me.
I truly appreciated.

**Comment by mschandler76** [comment]
Not a problem at all, when you need me to test something just let me know.

**Comment by Xstar97** [comment]
That will be great...if you can email your email info to me so I can add it
to the official google play closed beta program for terminal installer
x...since I don't have an actual Samsung device to test on...it would be
great to test before launch...so my email is miller97corey@gmail.com

**Comment by Xstar97** [comment]
So I found the bug...it was a boolean that was created for samsung sdk21 users...since the xposed framework wasnt installed...the boolean malfunction & started crashing the app..so i am now fixing it & will release an official beta for today & update tomorrow if it goes well(Possubly updating today...so other users can finally use this again)

**Comment by Xstar97** [comment]
the boolean activated no matter what sdk/manufacturer you had or if the framework was installed or not...it took me a day to really get this stupid thiing done...

**Comment by mschandler76** [comment]
Cool, so obviously you had to do some digging. Glad I could help out
SLIGHTLY, I wonder how many other Samsung phones that affected? No one
complained that Ive heard at least. Let me know when you want to test and
I'll give it a go.

**Comment by Xstar97** [comment]
That's the problem usually no one reports issues & just uninstall the app

**Comment by Xstar97** [comment]
Actually if wasnt for you...I would never had figured out the actual issue...I kept changing the wrong stuff...thinking it would work, but you did give me a huge push in the right direction..I just took a detour..so this will be the final apk link you can try & you wil be officially added to my closed beta test program...

but since your phone is a sdk21 arm device....the only compatible framework varient available is art97's(deprecated) & dkcldark's experimental test version 85...so I don't have any control over the compatibility for devices with the developers of the frameworks & I can not guaranteed it will work...so since you have a samsung...do you know to unbrick it if one occurs?

here's the fixed apk...hopefully...
http://www.mediafire.com/download/f7khujqbmma7wfx/app.apk

**Comment by mschandler76** [comment]
Yeah. Just unbricked it last week. That's what happened when I was messing
with my build.prop.

**Comment by mschandler76** [comment]
Ok no freezing. But it didn't install, I saw just before the script closed
it said xposed.prop not found?

**Comment by Xstar97** [comment]
Give me a sec to change a method & what version of busybox you have installed & where was it installed?

**Comment by Xstar97** [comment]
here's the link to beta test program too
only you will be able to sign up for it though...https://play.google.com/apps/testing/com.mcs.txi/join

**Comment by mschandler76** [comment]
I've got stericsons 1.24.2 in system/xbin

**Comment by Xstar97** [comment]
Okay this has always been an issue with SDK 22 & under so I just made the
fixed & will upload a new link(I won't use the beta program yet) so brb in
a few

**Comment by Xstar97** [comment]
http://www.mediafire.com/download/7vcomnbf7c0a0af/app.apk

**Comment by mschandler76** [comment]
Well we got a winner. Only thing I ran into was after it installed the
framework, everything started Unfortunately, this app or that app closed,
with ok and report. So I rebooted thinking I need to clear my dalvik, but
it did it for me so the sudden closes made since. Everything is good now.
On Jul 11, 2016 8:16 PM, "Xstar97" <notifications@github.com> wrote:

http://www.mediafire.com/download/7vcomnbf7c0a0af/app.apk

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Xstar97/TXI/issues/72#issuecomment-231903267>, or mute
the thread
<https://github.com/notifications/unsubscribe/ATa3FXv4eiFoZSEhFvkOgS9Lnl3c4kVRks5qUtzTgaJpZM4JIq7_>
.

**Comment by Xstar97** [comment]
So everything works & no issues what so ever?
Okay so @Midnight I will send out the update

**Comment by mschandler76** [comment]
Nope none at all so far. Ill mess around for a while and see if I can find
anything. But I think it's solid.

**Comment by Xstar97** [comment]
okay...so I will be closing this now...if you run into any issues...just report it & thanks for being very spefic it actually helped a lot to debug my tool!
