### ISSUE TITLE
Crashed on newbie

### ISSUE THREAD

**Issue by geoneo3477** [Xstar97/TXI#88]
I have been trying to root phones and he'll is what I got

Debug info:
 OS Version: 3.10.49-perf-ge03a442(765079.25)
 OS API Level: 23
 Device: htc_a16ul
 Model (and Product): HTC 2PST2 (a16ul_00531)
 RELEASE: 6.0.1
 BRAND: htc
 DISPLAY: MMB29M release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: htc_a16
 MANUFACTURER: HTC

Extra Info: 
Framework is NOT installed!
APP Version: 3.2.3
Xposed Installer app Version: 2.7 experimental1 is installed!
NOT rooted!
null
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
stack.trace does NOT exist

**Comment by Xstar97** [comment]
This tool doesnt root your device....it installs the xposed framework which REQURIES root....so sorry... the only way I can help is by offering kingoroot/kingroot those apps may be able to root your device
