### ISSUE TITLE
Directory not found on LG K7

### ISSUE THREAD

**Issue by LUModder** [Xstar97/TXI#91]
Weird that I'm getting directory issue on my K7 since you use it yourself. I have BusyBox and everything says compatible but it can't find the data directory for the app.

I have the MetroPCS MS330 version of the K7.

**Comment by LUModder** [comment]
Debug info:
!()[https://my.mixtape.moe/bdlvlc.png]

**Comment by LUModder** [comment]
Pretty sure this is a dupe isn't it.

**Comment by LUModder** [comment]
Found a fix. su can't read linked directories for some reason. Do /storage/emulated/0/ instead of /sdcard/

**Comment by Xstar97** [comment]
the issue is with lollipop sdk 22 which doesnt understand the cd method which the scripts tries to use...I believe I fixed it, however after transitions from AIDE to Android Studio...my signing key was not valid all this time...so I have to rebuild the entire app with a new signing key & app ID...I am almost done....Just have to retranslate the app again & implement some small stuff.

**Comment by Xstar97** [comment]
This is what the new UI looks like now
![screenshot_2016-08-14-14-04-21](https://cloud.githubusercontent.com/assets/9399967/17719684/7e155dec-63ea-11e6-9639-cc83cd4519c6.png)
![screenshot_2016-08-15-00-06-24](https://cloud.githubusercontent.com/assets/9399967/17719688/7e1e9aa6-63ea-11e6-95d4-a435a8acabc9.png)
![screenshot_2016-08-16-19-47-23](https://cloud.githubusercontent.com/assets/9399967/17719686/7e1ad39e-63ea-11e6-9dd8-efea78252273.png)
![screenshot_2016-08-16-19-47-28](https://cloud.githubusercontent.com/assets/9399967/17719687/7e1aeffa-63ea-11e6-9084-51b5fb567839.png)
![screenshot_2016-08-16-19-47-33](https://cloud.githubusercontent.com/assets/9399967/17719685/7e1a61b6-63ea-11e6-880d-1e93b8dbe981.png)
![screenshot_2016-08-16-19-47-37](https://cloud.githubusercontent.com/assets/9399967/17719689/7e20dfb4-63ea-11e6-80e5-fffd40b7e3f9.png)
![screenshot_2016-08-16-19-47-40](https://cloud.githubusercontent.com/assets/9399967/17719691/7e2166a0-63ea-11e6-9ba1-085632d57d21.png)
![screenshot_2016-08-16-19-47-43](https://cloud.githubusercontent.com/assets/9399967/17719690/7e210a52-63ea-11e6-845f-1545895549b5.png)
![screenshot_2016-08-16-19-47-48](https://cloud.githubusercontent.com/assets/9399967/17719692/7e21ec1a-63ea-11e6-85f4-bacd343152c7.png)

**Comment by LUModder** [comment]
Looks good so far. Sucks that you had to redo it though cause of the port. I was able to get it to install by manually running the script via terminal emulator and everything is working well. Wish you the best of luck on the app.

(Hope you don't mind me derailing but I was wondering what you used for the custom navbar)

**Comment by Xstar97** [comment]
I removed it the navbar to gain more space...Its just a textview with a list separator textview....

                               <TextView
			        android:layout_height="wrap_content"
				style="?android:attr/listSeparatorTextViewStyle"
				android:layout_width="match_parent"
				android:textColor="#000000"
				android:text="your title here"
				android:id="@+id/"name"_title_textView"/>

**Comment by LUModder** [comment]
I meant system navbar for home, back, etc.

**Comment by Xstar97** [comment]
its app called xstana(need xposed...)

**Comment by Xstar97** [comment]
if you dont mind, but once I recreate the app stuff on google play, would you like to join my beta team?

**Comment by LUModder** [comment]
Sure

**Comment by Xstar97** [comment]
whats your email?

**Comment by LUModder** [comment]
lumodder@gmail.com

**Comment by Xstar97** [comment]
thanks!

**Comment by Xstar97** [comment]
for security reasons I removed the comments

**Comment by LUModder** [comment]
Thats fine

**Comment by Xstar97** [comment]
sometime soon this week(probably) I will upload a beta for you to test

**Comment by Xstar97** [comment]
okay, the last thing I have to do is add more translations then do a in-house test & finally upload a beta for you test & v86 has been out, released for multiple variants & waiting to release them alongside the new Terminal Installer X 2.0 so very sorry for the delay.

**Comment by Xstar97** [comment]
also for some reason /sdcard/ actually used to work on sdk 21 & 22 & not getExternalstorage(/storage/emulated/0).....that's why I switched getExternalstorage with /sdcard/ on only sdk 22 & 21...however the new app will allow you to change the CD method to /sdcard/ or /mnt/  or /storage/(default)

**Comment by Xstar97** [comment]
Here's the link to the beta for the new app(required to sign up to get the beta): 
https://play.google.com/apps/testing/com.mcs.terminalinstallerx
