### ISSUE TITLE
Test: updater

### ISSUE THREAD

**Issue by Xstar97** [Xstar97/TXI#99]
testing the info updater crash

Debug info:
 OS Version: 3.10.49-ge4f6464(153571544a5ad)
 OS API Level: 22
 Device: m1
 Model (and Product): LGMS330 (m1_mpcs_us)
 RELEASE: 5.1.1
 BRAND: MetroPCS
 DISPLAY: LMY47V
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: m1
 MANUFACTURER: LGE

Extra Info: 
Framework is installed!
APP Version: 1.0
Xposed Installer app Version: 3.0 alpha4 is installed!
is rooted!
Busybox utilities are installed!
cd Info: path doesnt exist
Dir Info: Dir doesnt exist
java.lang.IllegalStateException: Fragment already added: DialogUpdate{ee247c6 #3 Update!}

--------- Stack trace ---------

    android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1357)
    android.support.v4.app.BackStackRecord.run(BackStackRecord.java:691)
    android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
    android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5422)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
    de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
-------------------------------

--------- Cause ---------

-------------------------------

**Comment by Xstar97** [comment]
@Umarkamboh
are you online still?

**Comment by Umarkamboh** [comment]
Yes... butt your app dosent work

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 16:52, Xstar97<notifications@github.com> wrote:   
@Umarkamboh
are you online still?

**Comment by Xstar97** [comment]
can you explain or report an issue from within my app?

**Comment by Umarkamboh** [comment]
This message show on screen..after this  it disappear 
Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 16:54, Xstar97<notifications@github.com> wrote:   
can you explain or report an issue from within my app?

**Comment by Xstar97** [comment]
I dont see a screenshot..but does it say "STDERR"?

**Comment by Xstar97** [comment]
This happens when the cd method wasnt compatible in the shell for some reason or another...so all you have to do is changed the cd method by tapping the current cd method & selecting a new one.

**Comment by Umarkamboh** [comment]
I dont understand this message.. how i can change current cd method..??

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 17:02, Xstar97<notifications@github.com> wrote:   
This happens when the cd method wasnt compatible in the shell for some reason or another...so all you have to do is changed the cd method by tapping the current cd method & selecting a new one.

**Comment by Xstar97** [comment]
which app did you download?
"Terminal Installer X" or "Terminal Installer X 2.0"

**Comment by Umarkamboh** [comment]
Installer x 2.0

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 17:07, Xstar97<notifications@github.com> wrote:   
which app did you download?
"Terminal Installer X" or "Terminal Installer X 2.0"

**Comment by Xstar97** [comment]
after tapping install on the main screen of TXI...a dialog will pop up download the framework if it wasnt downloaded before then a new dialog will pop up with the script info such as name, compatibility, cd method used, the script file, & execute button.
Tap the "/storage/ cd method" & tap "/sdcard/ cd method" & finally tap execute script

**Comment by Xstar97** [comment]
are you still having trouble?

**Comment by Umarkamboh** [comment]
Yes.... i used both storage/cd method & mnt/cd method. But its not work.. just disappear pop up dialog..

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 17:20, Xstar97<notifications@github.com> wrote:   
are you still having trouble?

**Comment by Xstar97** [comment]
can you take a screenshot of the error & upload on here?

**Comment by Xstar97** [comment]
Do you have root?

**Comment by Umarkamboh** [comment]
This pop up dialog appear and while it disappear.. thats it
Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 17:32, Xstar97<notifications@github.com> wrote:   
can you take a screenshot of the error & upload on here?

**Comment by Umarkamboh** [comment]
Yes.... rooted and deodex custom rom

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 17:42, Xstar97<notifications@github.com> wrote:   
Do you have root?

**Comment by Xstar97** [comment]
can you report an issue within my tool by going to "manage" & then tap "report issue"?
by reporting an issue it will collect device info & other info for me to debug the issue such as the first post of this issue

**Comment by Xstar97** [comment]
@Umarkamboh 
Are you having trouble reporting an issue?

**Comment by Umarkamboh** [comment]
I sent to you a  report..

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 17:58, Xstar97<notifications@github.com> wrote:   
@Umarkamboh 
Are you having trouble reporting an issue?
